/* Generated By:JavaCC: Do not edit this line. EvalConstants.java */
package descending;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EvalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int num = 1;
  /** RegularExpression Id. */
  int bool = 2;
  /** RegularExpression Id. */
  int letra = 3;
  /** RegularExpression Id. */
  int dig = 4;
  /** RegularExpression Id. */
  int p_ent = 5;
  /** RegularExpression Id. */
  int p_dec = 6;
  /** RegularExpression Id. */
  int p_exp = 7;
  /** RegularExpression Id. */
  int lit_n = 8;
  /** RegularExpression Id. */
  int or = 9;
  /** RegularExpression Id. */
  int and = 10;
  /** RegularExpression Id. */
  int not = 11;
  /** RegularExpression Id. */
  int v_boolean = 12;
  /** RegularExpression Id. */
  int ID = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"num\"",
    "\"bool\"",
    "<letra>",
    "<dig>",
    "<p_ent>",
    "<p_dec>",
    "<p_exp>",
    "<lit_n>",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "<v_boolean>",
    "<ID>",
    "<token of kind 14>",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"!=\"",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
