
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Apr 03 18:42:08 CEST 2019
//----------------------------------------------------

package ascending.lexical;

/** CUP generated class containing symbol constants. */
public class LexicalClass {
  /* terminals */
  public static final int OPEN_PARENTHESIS = 21;
  public static final int SEMICOLON = 4;
  public static final int OP_AND = 12;
  public static final int VALUE_FALSE = 25;
  public static final int OP_LESSER_EQUAL = 16;
  public static final int IDENTIFIER = 5;
  public static final int OP_NOT = 14;
  public static final int OP_OR = 13;
  public static final int NUM = 2;
  public static final int OP_SUB = 9;
  public static final int OP_GREATER = 17;
  public static final int EOF = 0;
  public static final int OP_LESSER = 15;
  public static final int SECTION_SEPARATOR = 6;
  public static final int VALUE_TRUE = 24;
  public static final int OP_GREATER_EQUAL = 18;
  public static final int OP_DIV = 11;
  public static final int OP_ADD = 8;
  public static final int error = 1;
  public static final int OP_EQUALS = 19;
  public static final int BOOL = 3;
  public static final int ASSIGNMENT = 7;
  public static final int CLOSE_PARENTHESIS = 22;
  public static final int OP_DIFFERENT = 20;
  public static final int LITERAL_NUMBER = 23;
  public static final int OP_MUL = 10;
}

