
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 06 19:09:52 CEST 2019
//----------------------------------------------------

package ascending.lexical;

/** CUP generated class containing symbol constants. */
public class LexicalClass {
  /* terminals */
  public static final int OPEN_PARENTHESIS = 7;
  public static final int SEMICOLON = 4;
  public static final int OP_AND = 16;
  public static final int OP_LESSER_EQUAL = 20;
  public static final int IDENTIFIER = 9;
  public static final int OP_NOT = 18;
  public static final int OP_OR = 17;
  public static final int NUM = 2;
  public static final int OP_SUB = 13;
  public static final int OP_GREATER = 21;
  public static final int EOF = 0;
  public static final int OP_LESSER = 19;
  public static final int SECTION_SEPARATOR = 5;
  public static final int OP_GREATER_EQUAL = 22;
  public static final int OP_DIV = 15;
  public static final int OP_ADD = 12;
  public static final int error = 1;
  public static final int OP_EQUALS = 23;
  public static final int BOOL = 3;
  public static final int ASSIGNMENT = 6;
  public static final int BOOLEAN_VALUE = 11;
  public static final int CLOSE_PARENTHESIS = 8;
  public static final int OP_DIFFERENT = 24;
  public static final int OP_MUL = 14;
  public static final int LITERAL_NUMBER = 10;
}

